### ISSUE TITLE
UTF-8 BOM mark on input causes parser crash (4.0.1)

### ISSUE THREAD

**Issue by wsb9** [stig/json-framework#195]

**Comment by srinivasgadda** [comment]
@wsb9 Do you have the similar issue what I shared here with the stacktrace https://github.com/stig/json-framework/issues/218 ?

**Comment by stig** [comment]
I plugged a file with a BOM into my test suite and it correctly rejected it at index 0 without crashing. I've got a PR for that here: https://github.com/stig/json-framework/pull/222 

It passed locally on my machine, and it passes for Mac target on Travis but I am currently struggling to get it to run on iOS on Travis. (This is most likely not due to the code being broken, but my config for running the tests.)

Anyway, I don't doubt that you saw an issue, but I'm unable to reproduce it I'm afraid. I'll leave it open in case anyone can shed some more light on the circumstances of it happening.

**Comment by stig** [comment]
I can't reproduce this, but I'll leave it open in case anyone wants to chime in with more information.

**Comment by wsb9** [comment]
Stig, I think we can safely close this. Crash occured more than year ago, on very old version of lib, and i have no code at my hands to test (project where i was experienced this is finished and closed). Test case and explicit no support for BOM is enough to treat issue as resolved. Thank you for all the work you did here!

**Comment by stig** [comment]
Thanks @wsb9, I missed that it was that long ago! 😳
